[build]
  base = "."
  publish = "apps/web/dist"
  command = "yarn workspace @trpc-template/server build && yarn workspace @trpc-template/client build && yarn workspace @trpc-template/web build"

[[redirects]]
  from = "/trpc/*"
  to = "https://multihopper-prod-db4f6830ced3.herokuapp.com/trpc/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
