export enum AuthMethod {
  EMAIL_PASSWORD = 'email_password',
  SOLANA_WALLET = 'solana_wallet',
  ETHEREUM_WALLET = 'ethereum_wallet',
  CUSTOM = 'custom'
}

export enum AuthErrorCode {
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  PROVIDER_ERROR = 'PROVIDER_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NETWORK_ERROR = 'NETWORK_ERROR',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR'
}

export const DEFAULT_JWT_EXPIRES_IN = '1h'
export const DEFAULT_REFRESH_TOKEN_EXPIRES_IN = '7d'
export const DEFAULT_SESSION_EXPIRES_IN = 7 * 24 * 60 * 60 * 1000 // 7 days in ms