import { db, NewHop, hopsSchema } from "../../db";
import {
  routesSchema,
  Routes,
  NewRoute,
  CreateRouteInput,
  RouteWithStatus,
} from "../schema/route.schema";
import { eq, and, lt } from "drizzle-orm";
import { CreateHopInput } from "../../hops/schema/hops.schema";
import { parseUserDateToUtc } from "../../utils/timezone";
import { isRouteDeployedOnChain } from "../../solana/services/contract.service";
import { obfuscationService } from "../../obfuscation";

// Helper to compute hop deltas (in ms) from absolute scheduledAt timestamps
function computeHopDeltasMs(hops: Array<{ scheduledAt: Date | string }>): number[] {
  return hops.map((hop, index, arr) => {
    if (index === 0) return 0;
    const prev = new Date(arr[index - 1].scheduledAt).getTime();
    const curr = new Date(hop.scheduledAt).getTime();
    const diff = Math.max(0, curr - prev);
    return diff;
  });
}

// Create a new route in the database (draft status) with timestamp-based hops
// New routes automatically have obfuscation enabled
const createRoute = async (input: CreateRouteInput): Promise<Routes> => {
  const route = await db.transaction(async (tx) => {
    // Create the route first with obfuscation enabled
    const newRoute: NewRoute = {
      // routeId will be auto-generated by the database
      name: input.name,
      description: input.description,
      tokenType: input.tokenType,
      tokenMint: input.tokenMint,
      tokenSymbol: input.tokenSymbol,
      tokenDecimals: input.tokenDecimals,
      hopAmountTokens: input.hopAmountTokens,
      hopAmountRaw: input.hopAmountRaw,
      isEasyRoute: input.isEasyRoute || false,
      hasObfuscation: true, // Always enable obfuscation for new routes
      creator: input.creator,
      status: "draft",
      // Legacy fields for backwards compatibility
      token: input.tokenMint || "SOL",
      amount: input.hopAmountRaw,
      pairMint: input.tokenMint || "",
      owner: input.creator,
      currentIndex: 0,
      lastIndex: input.hops.length - 1,
    };

    const [route] = await tx.insert(routesSchema).values(newRoute).returning();

    // Create the hops relationally with timestamps
    if (input.hops && input.hops.length > 0) {
      const hopsToCreate: CreateHopInput[] = input.hops.map((hop, index) => ({
        routeId: route.id,
        hopIndex: index,
        recipient: hop.recipient,
        scheduledAt: parseUserDateToUtc(hop.scheduledAt),
      }));

      await tx.insert(hopsSchema).values(hopsToCreate);
    }

    return route;
  });

  // Create obfuscation session for the new route (outside transaction)
  try {
    await obfuscationService.createSession({
      routeId: route.id,
      tokenMint: input.tokenMint,
      tokenType: input.tokenType,
      totalAmount: input.hopAmountRaw,
    });
  } catch (error) {
    // Re-throw error to fail route creation - obfuscation is required
    throw error;
  }

  return route;
};

/**
 * Replay an existing route by cloning it and re-basing hop times to now while preserving deltas.
 * - First hop scheduledAt = now
 * - Each subsequent hop = previous new time + original delta
 */
const replayRoute = async (id: number, creator: string): Promise<RouteWithStatus> => {
  // Load existing route with hops for this creator
  const existing = await db.query.routesSchema.findFirst({
    where: and(eq(routesSchema.id, id), eq(routesSchema.creator, creator)),
    with: {
      hops: {
        orderBy: (hops, { asc }) => [asc(hops.hopIndex)],
      },
    },
  });

  if (!existing) {
    throw new Error("Route not found");
  }

  const hops = existing.hops ?? [];
  if (hops.length === 0) {
    throw new Error("Cannot replay a route without hops");
  }

  // Compute deltas from original absolute timestamps
  const deltasMs = computeHopDeltasMs(hops);
  const nowMs = Date.now();

  // Build new hops array with scheduledAt starting from now
  const newHops = deltasMs.map((_deltaMs, index) => {
    const scheduledAt =
      index === 0
        ? nowMs
        : nowMs +
          deltasMs.slice(1, index + 1).reduce((a, b) => a + b, 0);
    return {
      recipient: hops[index].recipient,
      scheduledAt: new Date(scheduledAt).toISOString(),
    };
  });

  // Create cloned route with same token settings and hop amounts
  const clonedInput: CreateRouteInput = {
    name: existing.name ? `${existing.name} (Replay ${new Date().toISOString()})` : undefined,
    description: existing.description ?? undefined,
    tokenType: existing.tokenType as "SPL" | "SOL",
    tokenDecimals: existing.tokenDecimals,
    hopAmountTokens: existing.hopAmountTokens,
    hopAmountRaw: existing.hopAmountRaw,
    hops: newHops,
    creator,
  };
  if (existing.tokenMint != null) {
    clonedInput.tokenMint = existing.tokenMint as string;
  }
  if (existing.tokenSymbol != null) {
    clonedInput.tokenSymbol = existing.tokenSymbol as string;
  }
  const cloned = await createRoute(clonedInput);

  const result = await getRoute(cloned.id, creator);
  if (!result) {
    throw new Error("Failed to load cloned route");
  }
  return result;
};

// Calculate delays from timestamps for display purposes
const calculateDelaysFromTimestamps = (
  hops: { recipient: string; scheduledAt: Date | string; [key: string]: any }[]
) => {
  return hops.map((hop, index, hops) => {
    let delayMinutes = 0;
    let delaySeconds = 0;

    if (index > 0) {
      const prevHopTime = new Date(hops[index - 1].scheduledAt).getTime();
      const currentHopTime = new Date(hop.scheduledAt).getTime();
      const diffMs = Math.max(0, currentHopTime - prevHopTime);
      delaySeconds = Math.floor(diffMs / 1000);
      delayMinutes = Math.floor(delaySeconds / 60);
    }

    return {
      recipient: hop.recipient,
      scheduledAt: hop.scheduledAt,
      delayMinutes,
      delaySeconds,
    };
  });
};

// Get routes for a specific creator with their timestamp-based hops
const getRoutesByCreatorPaginated = async ({
  creator,
  cursor,
  limit
}: {
  creator: string;
  cursor?: number | null;
  limit: number;
}): Promise<{ data: RouteWithStatus[]; nextCursor: number | null }> => {

  // Fetch +1 so we know there is a next page
  const routesWithHops = await db.query.routesSchema.findMany({
    where: and(
      eq(routesSchema.creator, creator),
      cursor ? lt(routesSchema.id, cursor) : undefined
    ),
    limit: limit + 1,
    orderBy: (routes, { desc }) => [desc(routes.id)],
    with: {
      hops: {
        orderBy: (hops, { asc }) => [asc(hops.hopIndex)],
      },
      obfuscationSession: true, // JOIN to get obfuscation status
    },
  });

  // Determine next cursor
  let nextCursor: number | null = null;
  if (routesWithHops.length > limit) {
    const nextItem = routesWithHops.pop(); // remove extra item
    nextCursor = nextItem!.id;
  }

  // Process each route as before
  const processed = await Promise.all(
    routesWithHops.map(async (route) => {
      const hopsWithDelays = route.hops
        ? calculateDelaysFromTimestamps(route.hops)
        : [];

      let isDeployed =
        route.status === "completed" || route.status === "deployed";

      if (route.status === "draft") {
        isDeployed = await isRouteDeployedOnChain(route.id);
      }

      return {
        ...route,
        canDeploy: !isDeployed,
        deploymentStatus: route.status as
          | "draft"
          | "deploying"
          | "deployed"
          | "completed"
          | "failed",
        obfuscationStatus: route.obfuscationSession?.status || null,
        hops: hopsWithDelays.map((hop) => ({
          recipient: hop.recipient,
          scheduledAt: new Date(hop.scheduledAt).toUTCString(),
          delayMinutes: hop.delayMinutes,
          delaySeconds: hop.delaySeconds,
        })),
      };
    })
  );

  return {
    data: processed,
    nextCursor,
  };
};

const getRouteById = async (id: number): Promise<RouteWithStatus | null> => {
  const route = await db.query.routesSchema.findFirst({
    where: eq(routesSchema.id, id),
  });
  if (!route) return null;
  return getRoute(route.id, route.creator);
};

// Get a specific route by ID and creator with timestamp-based hops
const getRoute = async (
  id: number,
  creator: string
): Promise<RouteWithStatus | null> => {
  const route = await db.query.routesSchema.findFirst({
    where: and(eq(routesSchema.id, id), eq(routesSchema.creator, creator)),
    with: {
      hops: {
        orderBy: (hops, { asc }) => [asc(hops.hopIndex)],
      },
    },
  });

  if (!route) return null;

  const hopsWithDelays = route.hops
    ? calculateDelaysFromTimestamps(route.hops)
    : [];
  let isDeployed = route.status === "completed" || route.status === "deployed";
  if (route.status === "draft") {
    isDeployed = await isRouteDeployedOnChain(route.id);
  }
  return {
    ...route,
    canDeploy: !isDeployed || route.status === "completed",
    deploymentStatus: route.status as
      | "draft"
      | "deploying"
      | "deployed"
      | "failed",
    hops: hopsWithDelays.map((hop) => ({
      recipient: hop.recipient,
      scheduledAt:
        hop.scheduledAt instanceof Date
          ? hop.scheduledAt.toISOString()
          : hop.scheduledAt,
      delayMinutes: hop.delayMinutes,
      delaySeconds: hop.delaySeconds,
    })),
  };
};

// Update route status
const updateRouteStatus = async (
  id: number,
  creator: string,
  status: "draft" | "deploying" | "deployed" | "completed" | "failed",
  deploymentData?: {
    deploymentTxHash?: string;
    routeConfigPda?: string;
    deploymentError?: string;
  }
): Promise<void> => {
  const updateData: Partial<NewRoute> = {
    status,
    updatedAt: new Date(),
  };

  if (status === "deployed" && deploymentData) {
    updateData.deployedAt = new Date();
    updateData.deploymentTxHash = deploymentData.deploymentTxHash;
    updateData.routeConfigPda = deploymentData.routeConfigPda;
    updateData.deploymentError = null;
  } else if (status === "failed" && deploymentData?.deploymentError) {
    updateData.deploymentError = deploymentData.deploymentError;
  }

  await db
    .update(routesSchema)
    .set(updateData)
    .where(and(eq(routesSchema.id, id), eq(routesSchema.creator, creator)));
};

// Delete a route (only if not deployed) - hops will be cascade deleted
const deleteRoute = async (id: number, creator: string): Promise<boolean> => {
  const route = await getRoute(id, creator);
  if (!route || route.status === "deployed") {
    return false; // Cannot delete deployed routes
  }

  const result = await db.delete(routesSchema).where(
    and(
      eq(routesSchema.id, id),
      eq(routesSchema.creator, creator),
      eq(routesSchema.status, "draft") // Extra safety check
    )
  );

  return (result.rowCount ?? 0) > 0;
};

// Update route details (only if not deployed) with timestamp-based hops cascade update
const updateRoute = async (
  id: number,
  creator: string,
  updates: Partial<CreateRouteInput>
): Promise<RouteWithStatus | null> => {
  const route = await getRoute(id, creator);
  if (!route || route.status === "deployed") {
    return null; // Cannot update deployed routes
  }

  return db.transaction(async (tx) => {
    // Update route details
    const updateData: Partial<NewRoute> = {
      name: updates.name,
      description: updates.description,
      tokenType: updates.tokenType,
      tokenMint: updates.tokenMint,
      tokenDecimals: updates.tokenDecimals,
      hopAmountTokens: updates.hopAmountTokens,
      hopAmountRaw: updates.hopAmountRaw,
      updatedAt: new Date(),
    };

    await tx
      .update(routesSchema)
      .set(updateData)
      .where(and(eq(routesSchema.id, id), eq(routesSchema.creator, creator)));

    // If hops are being updated, replace them with timestamp-based hops
    if (updates.hops) {
      // Delete existing hops
      await tx.delete(hopsSchema).where(eq(hopsSchema.routeId, id));

      // Create new timestamp-based hops
      if (updates.hops.length > 0) {
        const hopsToCreate: CreateHopInput[] = updates.hops.map(
          (hop, index) => ({
            routeId: id,
            hopIndex: index,
            recipient: hop.recipient,
            scheduledAt: parseUserDateToUtc(hop.scheduledAt),
          })
        );

        await tx.insert(hopsSchema).values(hopsToCreate);
      }
    }

    return getRoute(id, creator);
  });
};

// Legacy functions (keep for backwards compatibility)
const cascadeCreate = async (_route: NewRoute, _hops: NewHop[]) => {
  return db.transaction(async (tx) => {
    const route = await tx.insert(routesSchema).values(_route).returning();
    const hops = await tx
      .insert(hopsSchema)
      .values(_hops.map((hop) => ({ ...hop, routeId: route[0].id })))
      .returning();
    return { route, hops };
  });
};

const triggerNextHop = async (routeId: number) => {
  // TODO: Implement hop triggering logic
};

// Update hop timestamps in the database (for fixing incomplete deployments)
const updateHopTimestamps = async (
  routeId: number,
  creator: string,
  hops: Array<{ recipient: string; scheduledAt: number }>
) => {
  return db.transaction(async (tx) => {
    // Verify the route belongs to this creator
    const route = await tx.query.routesSchema.findFirst({
      where: and(eq(routesSchema.id, routeId), eq(routesSchema.creator, creator)),
    });

    if (!route) {
      throw new Error("Route not found or unauthorized");
    }

    // Delete existing hops
    await tx.delete(hopsSchema).where(eq(hopsSchema.routeId, routeId));

    // Insert new hops with updated timestamps
    const hopsToCreate: CreateHopInput[] = hops.map((hop, index) => ({
      routeId: routeId,
      hopIndex: index,
      recipient: hop.recipient,
      scheduledAt: new Date(hop.scheduledAt), // Convert ms timestamp to Date
    }));

    await tx.insert(hopsSchema).values(hopsToCreate);
  });
};

const routesService = {
  createRoute,
  getRoutesByCreatorPaginated,
  getRoute,
  updateRouteStatus,
  replayRoute,
  deleteRoute,
  updateRoute,
  updateHopTimestamps,
  // Legacy functions
  cascadeCreate,
  getRouteById,
  triggerNextHop,
};

export default routesService;
