import { db, NewHop, hopsSchema } from "../../db";
import {
  routesSchema,
  Routes,
  NewRoute,
  CreateRouteInput,
  RouteWithStatus,
} from "../schema/route.schema";
import { eq, and } from "drizzle-orm";
import { CreateHopInput } from "../../hops/schema/hops.schema";
import { parseUserDateToUtc } from "../../utils/timezone";
import { isRouteDeployedOnChain } from "../../solana/services/contract.service";

// Create a new route in the database (draft status) with timestamp-based hops
const createRoute = async (input: CreateRouteInput): Promise<Routes> => {
  return db.transaction(async (tx) => {
    // Create the route first
    const newRoute: NewRoute = {
      // routeId will be auto-generated by the database
      name: input.name,
      description: input.description,
      tokenType: input.tokenType,
      tokenMint: input.tokenMint,
      tokenDecimals: input.tokenDecimals,
      hopAmountTokens: input.hopAmountTokens,
      hopAmountRaw: input.hopAmountRaw,
      creator: input.creator,
      status: "draft",
      // Legacy fields for backwards compatibility
      token: input.tokenMint || "SOL",
      amount: input.hopAmountRaw,
      pairMint: input.tokenMint || "",
      owner: input.creator,
      currentIndex: 0,
      lastIndex: input.hops.length - 1,
    };

    const [route] = await tx.insert(routesSchema).values(newRoute).returning();

    // Create the hops relationally with timestamps
    if (input.hops && input.hops.length > 0) {
      const hopsToCreate: CreateHopInput[] = input.hops.map((hop, index) => ({
        routeId: route.id,
        hopIndex: index,
        recipient: hop.recipient,
        scheduledAt: parseUserDateToUtc(hop.scheduledAt),
      }));

      await tx.insert(hopsSchema).values(hopsToCreate);
    }

    return route;
  });
};

// Calculate delays from timestamps for display purposes
const calculateDelaysFromTimestamps = (
  hops: { recipient: string; scheduledAt: Date | string; [key: string]: any }[]
) => {
  return hops.map((hop, index, hops) => {
    let delayMinutes = 0;
    let delaySeconds = 0;

    if (index > 0) {
      const prevHopTime = new Date(hops[index - 1].scheduledAt).getTime();
      const currentHopTime = new Date(hop.scheduledAt).getTime();
      const diffMs = Math.max(0, currentHopTime - prevHopTime);
      delaySeconds = Math.floor(diffMs / 1000);
      delayMinutes = Math.floor(delaySeconds / 60);
    }

    return {
      recipient: hop.recipient,
      scheduledAt: hop.scheduledAt,
      delayMinutes,
      delaySeconds,
    };
  });
};

// Get routes for a specific creator with their timestamp-based hops
const getRoutesByCreator = async (
  creator: string
): Promise<RouteWithStatus[]> => {
  const routesWithHops = await db.query.routesSchema.findMany({
    where: eq(routesSchema.creator, creator),
    with: {
      hops: {
        orderBy: (hops, { asc }) => [asc(hops.hopIndex)],
      },
    },
    orderBy: (routes, { desc }) => [desc(routes.createdAt)],
  });

  return Promise.all(
    routesWithHops.map(async (route) => {
      const hopsWithDelays = route.hops
        ? calculateDelaysFromTimestamps(route.hops)
        : [];
      console.log(`Route ${route.id} status: ${route.status}`);
      let isDeployed =
        route.status === "completed" || route.status === "deployed";
      if (route.status === "draft") {
        isDeployed = await isRouteDeployedOnChain(route.id);
      }
      return {
        ...route,
        canDeploy: !isDeployed,
        deploymentStatus: route.status as
          | "draft"
          | "deploying"
          | "deployed"
          | "failed",
        hops: hopsWithDelays.map((hop) => ({
          recipient: hop.recipient,
          scheduledAt: new Date(hop.scheduledAt).toUTCString(),
          delayMinutes: hop.delayMinutes,
          delaySeconds: hop.delaySeconds,
        })),
      };
    })
  );
};

const getRouteById = async (id: number): Promise<RouteWithStatus | null> => {
  const route = await db.query.routesSchema.findFirst({
    where: eq(routesSchema.id, id),
  });
  if (!route) return null;
  return getRoute(route.id, route.creator);
};

// Get a specific route by ID and creator with timestamp-based hops
const getRoute = async (
  id: number,
  creator: string
): Promise<RouteWithStatus | null> => {
  const route = await db.query.routesSchema.findFirst({
    where: and(eq(routesSchema.id, id), eq(routesSchema.creator, creator)),
    with: {
      hops: {
        orderBy: (hops, { asc }) => [asc(hops.hopIndex)],
      },
    },
  });

  if (!route) return null;

  const hopsWithDelays = route.hops
    ? calculateDelaysFromTimestamps(route.hops)
    : [];
  let isDeployed = route.status === "completed" || route.status === "deployed";
  if (route.status === "draft") {
    isDeployed = await isRouteDeployedOnChain(route.id);
  }
  return {
    ...route,
    canDeploy: !isDeployed || route.status === "completed",
    deploymentStatus: route.status as
      | "draft"
      | "deploying"
      | "deployed"
      | "failed",
    hops: hopsWithDelays.map((hop) => ({
      recipient: hop.recipient,
      scheduledAt:
        hop.scheduledAt instanceof Date
          ? hop.scheduledAt.toISOString()
          : hop.scheduledAt,
      delayMinutes: hop.delayMinutes,
      delaySeconds: hop.delaySeconds,
    })),
  };
};

// Update route status
const updateRouteStatus = async (
  id: number,
  creator: string,
  status: "draft" | "deploying" | "deployed" | "failed",
  deploymentData?: {
    deploymentTxHash?: string;
    routeConfigPda?: string;
    deploymentError?: string;
  }
): Promise<void> => {
  const updateData: Partial<NewRoute> = {
    status,
    updatedAt: new Date(),
  };

  if (status === "deployed" && deploymentData) {
    updateData.deployedAt = new Date();
    updateData.deploymentTxHash = deploymentData.deploymentTxHash;
    updateData.routeConfigPda = deploymentData.routeConfigPda;
    updateData.deploymentError = null;
  } else if (status === "failed" && deploymentData?.deploymentError) {
    updateData.deploymentError = deploymentData.deploymentError;
  }

  await db
    .update(routesSchema)
    .set(updateData)
    .where(and(eq(routesSchema.id, id), eq(routesSchema.creator, creator)));
};

// Delete a route (only if not deployed) - hops will be cascade deleted
const deleteRoute = async (id: number, creator: string): Promise<boolean> => {
  const route = await getRoute(id, creator);
  if (!route || route.status === "deployed") {
    return false; // Cannot delete deployed routes
  }

  const result = await db.delete(routesSchema).where(
    and(
      eq(routesSchema.id, id),
      eq(routesSchema.creator, creator),
      eq(routesSchema.status, "draft") // Extra safety check
    )
  );

  return (result.rowCount ?? 0) > 0;
};

// Update route details (only if not deployed) with timestamp-based hops cascade update
const updateRoute = async (
  id: number,
  creator: string,
  updates: Partial<CreateRouteInput>
): Promise<RouteWithStatus | null> => {
  const route = await getRoute(id, creator);
  if (!route || route.status === "deployed") {
    return null; // Cannot update deployed routes
  }

  return db.transaction(async (tx) => {
    // Update route details
    const updateData: Partial<NewRoute> = {
      name: updates.name,
      description: updates.description,
      tokenType: updates.tokenType,
      tokenMint: updates.tokenMint,
      tokenDecimals: updates.tokenDecimals,
      hopAmountTokens: updates.hopAmountTokens,
      hopAmountRaw: updates.hopAmountRaw,
      updatedAt: new Date(),
    };

    await tx
      .update(routesSchema)
      .set(updateData)
      .where(and(eq(routesSchema.id, id), eq(routesSchema.creator, creator)));

    // If hops are being updated, replace them with timestamp-based hops
    if (updates.hops) {
      // Delete existing hops
      await tx.delete(hopsSchema).where(eq(hopsSchema.routeId, id));

      // Create new timestamp-based hops
      if (updates.hops.length > 0) {
        const hopsToCreate: CreateHopInput[] = updates.hops.map(
          (hop, index) => ({
            routeId: id,
            hopIndex: index,
            recipient: hop.recipient,
            scheduledAt: parseUserDateToUtc(hop.scheduledAt),
          })
        );

        await tx.insert(hopsSchema).values(hopsToCreate);
      }
    }

    return getRoute(id, creator);
  });
};

// Legacy functions (keep for backwards compatibility)
const cascadeCreate = async (_route: NewRoute, _hops: NewHop[]) => {
  return db.transaction(async (tx) => {
    const route = await tx.insert(routesSchema).values(_route).returning();
    const hops = await tx
      .insert(hopsSchema)
      .values(_hops.map((hop) => ({ ...hop, routeId: route[0].id })))
      .returning();
    return { route, hops };
  });
};

const triggerNextHop = async (routeId: number) => {
  // TODO: Implement hop triggering logic
  console.log(`Triggering next hop for route ${routeId}`);
  // Implementation for triggering next hop
};

const routesService = {
  createRoute,
  getRoutesByCreator,
  getRoute,
  updateRouteStatus,
  deleteRoute,
  updateRoute,
  // Legacy functions
  cascadeCreate,
  getRouteById,
  triggerNextHop,
};

export default routesService;
